### ISSUE TITLE
Broken UI

### ISSUE THREAD

**Issue by jon-dan** [olinic/uMetronome#7]
Since the last update the UI is broken on the RC-proposed channel. Everything works fine using qmlscene on the desktop.

![screenshot20151014_210249996](https://cloud.githubusercontent.com/assets/747240/10502177/46607794-72b7-11e5-839d-19802ffd493f.png)

Log file: http://paste.ubuntu.com/12785255

**Comment by olinic** [comment]
Issue fixed by including sound and icon files in cmake file.

**Comment by olinic** [comment]
Moved to qmake. Sound and icon files specified in .pro file so they are not missing on install.
